/** @type {import('tailwindcss').Config} config */

const plugin = require('tailwindcss/plugin');
const typography = require('@tailwindcss/typography');

const config = {
  content: ['./app/**/*.php', './resources/**/*.{php,vue,js,ts}', './../../../../vendor/agence-adeliom/horizon-blocks/resources/views/**/*.blade.php'],
  safelist: [
    'basis-1/2 lg:basis-1/3 lg:basis-1/4',
  ],
  future: {
    hoverOnlyWhenSupported: true,
  },
  theme: {
    extend: {
      colors: {
        text: {
          primary: 'var(--awc-text-primary-color)',
          secondary: 'var(--awc-text-secondary-color)',
        },
        background: {
          DEFAULT: 'var(--awc-background-color)',
        },
        primary: {
          DEFAULT: 'var(--awc-color-primary-main)',
          dark: 'var(--awc-color-primary-dark)',
          light: 'var(--awc-color-primary-light)',
          contrast: 'var(--awc-color-primary-contrast)',
          states: {
            selected: 'var(--awc-color-primary-states-selected)',
            hover: 'var(--awc-color-primary-states-hover)',
            focus: 'var(--awc-color-primary-states-focus)',
            'focus-visible': 'var(--awc-color-primary-states-focus-visible)',
            'outlined-border': 'var(--awc-color-primary-states-outlined-border)',
          },
        },
        secondary: {
          DEFAULT: 'var(--awc-color-secondary-main)',
          dark: 'var(--awc-color-secondary-dark)',
          light: 'var(--awc-color-secondary-light)',
          contrast: 'var(--awc-color-secondary-contrast)',
          states: {
            selected: 'var(--awc-color-secondary-states-selected)',
            hover: 'var(--awc-color-secondary-states-hover)',
            focus: 'var(--awc-color-secondary-states-focus)',
            'focus-visible': 'var(--awc-color-secondary-states-focus-visible)',
            'outlined-border': 'var(--awc-color-secondary-states-outlined-border)',
          },
        },
        tertiary: {
          DEFAULT: 'var(--awc-color-tertiary-main)',
          dark: 'var(--awc-color-tertiary-dark)',
          light: 'var(--awc-color-tertiary-light)',
          contrast: 'var(--awc-color-tertiary-contrast)',
          states: {
            selected: 'var(--awc-color-tertiary-states-selected)',
            hover: 'var(--awc-color-tertiary-states-hover)',
            focus: 'var(--awc-color-tertiary-states-focus)',
            'focus-visible': 'var(--awc-color-tertiary-states-focus-visible)',
            'outlined-border': 'var(--awc-color-tertiary-states-outlined-border)',
          },
        },
        danger: {
          DEFAULT: 'var(--awc-color-danger-main)',
          dark: 'var(--awc-color-danger-dark)',
          light: 'var(--awc-color-danger-light)',
          contrast: 'var(--awc-color-danger-contrast)',
          states: {
            selected: 'var(--awc-color-danger-states-selected)',
            hover: 'var(--awc-color-danger-states-hover)',
            focus: 'var(--awc-color-danger-states-focus)',
            'focus-visible': 'var(--awc-color-danger-states-focus-visible)',
            'outlined-border': 'var(--awc-color-danger-states-outlined-border)',
          },
        },
        warning: {
          DEFAULT: 'var(--awc-color-warning-main)',
          dark: 'var(--awc-color-warning-dark)',
          light: 'var(--awc-color-warning-light)',
          contrast: 'var(--awc-color-warning-contrast)',
          states: {
            selected: 'var(--awc-color-warning-states-selected)',
            hover: 'var(--awc-color-warning-states-hover)',
            focus: 'var(--awc-color-warning-states-focus)',
            'focus-visible': 'var(--awc-color-warning-states-focus-visible)',
            'outlined-border': 'var(--awc-color-warning-states-outlined-border)',
          },
        },
        success: {
          DEFAULT: 'var(--awc-color-success-main)',
          dark: 'var(--awc-color-success-dark)',
          light: 'var(--awc-color-success-light)',
          contrast: 'var(--awc-color-success-contrast)',
          states: {
            selected: 'var(--awc-color-success-states-selected)',
            hover: 'var(--awc-color-success-states-hover)',
            focus: 'var(--awc-color-success-states-focus)',
            'focus-visible': 'var(--awc-color-success-states-focus-visible)',
            'outlined-border': 'var(--awc-color-success-states-outlined-border)',
          },
        },
        gray: {
          50: 'var(--awc-color-gray-50)',
          100: 'var(--awc-color-gray-100)',
          200: 'var(--awc-color-gray-200)',
          300: 'var(--awc-color-gray-300)',
          400: 'var(--awc-color-gray-400)',
          500: 'var(--awc-color-gray-500)',
          600: 'var(--awc-color-gray-600)',
          700: 'var(--awc-color-gray-700)',
          800: 'var(--awc-color-gray-800)',
          900: 'var(--awc-color-gray-900)',
          950: 'var(--awc-color-gray-950)',
        },
        red: {
          50: 'var(--awc-color-red-50)',
          100: 'var(--awc-color-red-100)',
          200: 'var(--awc-color-red-200)',
          300: 'var(--awc-color-red-300)',
          400: 'var(--awc-color-red-400)',
          500: 'var(--awc-color-red-500)',
          600: 'var(--awc-color-red-600)',
          700: 'var(--awc-color-red-700)',
          800: 'var(--awc-color-red-800)',
          900: 'var(--awc-color-red-900)',
          950: 'var(--awc-color-red-950)',
        },
        green: {
          50: 'var(--awc-color-green-50)',
          100: 'var(--awc-color-green-100)',
          200: 'var(--awc-color-green-200)',
          300: 'var(--awc-color-green-300)',
          400: 'var(--awc-color-green-400)',
          500: 'var(--awc-color-green-500)',
          600: 'var(--awc-color-green-600)',
          700: 'var(--awc-color-green-700)',
          800: 'var(--awc-color-green-800)',
          900: 'var(--awc-color-green-900)',
          950: 'var(--awc-color-green-950)',
        },
        orange: {
          50: 'var(--awc-color-orange-50)',
          100: 'var(--awc-color-orange-100)',
          200: 'var(--awc-color-orange-200)',
          300: 'var(--awc-color-orange-300)',
          400: 'var(--awc-color-orange-400)',
          500: 'var(--awc-color-orange-500)',
          600: 'var(--awc-color-orange-600)',
          700: 'var(--awc-color-orange-700)',
          800: 'var(--awc-color-orange-800)',
          900: 'var(--awc-color-orange-900)',
          950: 'var(--awc-color-orange-950)',
        },
        'color-01': {
          50: 'var(--awc-color-color-01-50)',
          100: 'var(--awc-color-color-01-100)',
          200: 'var(--awc-color-color-01-200)',
          300: 'var(--awc-color-color-01-300)',
          400: 'var(--awc-color-color-01-400)',
          500: 'var(--awc-color-color-01-500)',
          600: 'var(--awc-color-color-01-600)',
          700: 'var(--awc-color-color-01-700)',
          800: 'var(--awc-color-color-01-800)',
          900: 'var(--awc-color-color-01-900)',
          950: 'var(--awc-color-color-01-950)',
          DEFAULT: 'var(--awc-color-color-01-default)',
        },
        'color-02': {
          50: 'var(--awc-color-color-02-50)',
          100: 'var(--awc-color-color-02-100)',
          200: 'var(--awc-color-color-02-200)',
          300: 'var(--awc-color-color-02-300)',
          400: 'var(--awc-color-color-02-400)',
          500: 'var(--awc-color-color-02-500)',
          600: 'var(--awc-color-color-02-600)',
          700: 'var(--awc-color-color-02-700)',
          800: 'var(--awc-color-color-02-800)',
          900: 'var(--awc-color-color-02-900)',
          950: 'var(--awc-color-color-02-950)',
          DEFAULT: 'var(--awc-color-color-02-default)',
        },
        'color-03': {
          50: 'var(--awc-color-color-03-50)',
          100: 'var(--awc-color-color-03-100)',
          200: 'var(--awc-color-color-03-200)',
          300: 'var(--awc-color-color-03-300)',
          400: 'var(--awc-color-color-03-400)',
          500: 'var(--awc-color-color-03-500)',
          600: 'var(--awc-color-color-03-600)',
          700: 'var(--awc-color-color-03-700)',
          800: 'var(--awc-color-color-03-800)',
          900: 'var(--awc-color-color-03-900)',
          950: 'var(--awc-color-color-03-950)',
          DEFAULT: 'var(--awc-color-color-03-default)',
        },
        neutral: {
          0: 'var(--awc-color-neutral-0)',
          50: 'var(--awc-color-neutral-50)',
          100: 'var(--awc-color-neutral-100)',
          200: 'var(--awc-color-neutral-200)',
          300: 'var(--awc-color-neutral-300)',
          400: 'var(--awc-color-neutral-400)',
          500: 'var(--awc-color-neutral-500)',
          600: 'var(--awc-color-neutral-600)',
          700: 'var(--awc-color-neutral-700)',
          800: 'var(--awc-color-neutral-800)',
          900: 'var(--awc-color-neutral-900)',
          950: 'var(--awc-color-neutral-950)',
          1000: 'var(--awc-color-neutral-1000)',
        },
        accent: 'var(--awc-text-accent-color)',
        transparent: 'var(--awc-color-transparent)',
        tooltip: 'var(--awc-tooltip-color)',
        'focus-ring': 'var(--awc-focus-ring-color)',
        input: {
          DEFAULT: 'var(--awc-input-color-default)',
          hover: 'var(--awc-input-color-hover)',
          focus: 'var(--awc-input-color-focus)',
          disabled: 'var(--awc-input-color-disabled)',
          placeholder: 'var(--awc-input-placeholder-color)',
          icon: 'var(--awc-input-icon-color)',
          filled: 'var(--awc-input-filled-color)',
          label: 'var(--awc-input-label-color)',
          'help-text': 'var(--awc-input-help-text-color)',
          'required-content': 'var(--awc-input-required-content-color)',
          'focus-ring': 'var(--awc-input-focus-ring-color)',
        }
      },
      backgroundColor: {
        overlay: 'var(--awc-overlay-background-color)',
        input: {
          DEFAULT: 'var(--awc-input-background-color-default)',
          filled: 'var(--awc-input-filled-background-color)',
          hover: 'var(--awc-input-background-color-hover)',
          focus: 'var(--awc-input-background-color-focus)',
          disabled: 'var(--awc-input-background-color-disabled)',
        },
        tooltip: 'var(--awc-tooltip-background-color)',
        panel: 'var(--awc-panel-background-color)',
        card: 'var(--awc-card-background-color)',
      },
      borderColor: {
        panel: 'var(--awc-panel-border-color)',
        card: 'var(--awc-card-border-color)',
        input: {
          DEFAULT: 'var(--awc-input-border-color-default)',
          hover: 'var(--awc-input-border-color-hover)',
          focus: 'var(--awc-input-border-color-focus)',
          disabled: 'var(--awc-input-border-color-disabled)',
        },
      },
      fontSize: {
        '2xsmall': 'var(--awc-font-size-2xsmall)',
        xs: 'var(--awc-font-size-xsmall)',
        xsmall: 'var(--awc-font-size-xsmall)',
        sm: 'var(--awc-font-size-small)',
        small: 'var(--awc-font-size-small)',
        md: 'var(--awc-font-size-medium)',
        medium: 'var(--awc-font-size-medium)',
        lg: 'var(--awc-font-size-large)',
        large: 'var(--awc-font-size-large)',
        xl: 'var(--awc-font-size-xlarge)',
        xlarge: 'var(--awc-font-size-xlarge)',
        '2xlarge': 'var(--awc-font-size-2xlarge)',
        '3xlarge': 'var(--awc-font-size-3xlarge)',
        '4xlarge': 'var(--awc-font-size-4xlarge)',
        '5xlarge': 'var(--awc-font-size-5xlarge)',
        '6xlarge': 'var(--awc-font-size-6xlarge)',
        '7xlarge': 'var(--awc-font-size-7xlarge)',
        '8xlarge': 'var(--awc-font-size-8xlarge)',
        '9xlarge': 'var(--awc-font-size-9xlarge)',
        '10xlarge': 'var(--awc-font-size-10xlarge)',
        base: 'var(--awc-font-size-base)',
        heading1: 'var(--awc-font-size-heading1)',
        heading2: 'var(--awc-font-size-heading2)',
        heading3: 'var(--awc-font-size-heading3)',
        heading4: 'var(--awc-font-size-heading4)',
        heading5: 'var(--awc-font-size-heading5)',
        heading6: 'var(--awc-font-size-heading6)',
        tooltip: 'var(--awc-tooltip-font-size)',
        'input-sm': 'var(--awc-input-font-size-small)',
        'input-md': 'var(--awc-input-font-size-medium)',
        'input-lg': 'var(--awc-input-font-size-large)',
        'input-label-sm': 'var(--awc-input-label-font-size-small)',
        'input-label-md': 'var(--awc-input-label-font-size-medium)',
        'input-label-lg': 'var(--awc-input-label-font-size-large)',
        'input-help-text-sm': 'var(--awc-input-help-text-font-size-small)',
        'input-help-text-md': 'var(--awc-input-help-text-font-size-medium)',
        'input-help-text-lg': 'var(--awc-input-help-text-font-size-large)',
      },
      spacing: {
        '3xsmall': 'var(--awc-spacing-3xsmall)',
        '2xsmall': 'var(--awc-spacing-2xsmall)',
        xsmall: 'var(--awc-spacing-xsmall)',
        small: 'var(--awc-spacing-small)',
        medium: 'var(--awc-spacing-medium)',
        large: 'var(--awc-spacing-large)',
        xlarge: 'var(--awc-spacing-xlarge)',
        '2xlarge': 'var(--awc-spacing-2xlarge)',
        '3xlarge': 'var(--awc-spacing-3xlarge)',
        '4xlarge': 'var(--awc-spacing-4xlarge)',
        '5xlarge': 'var(--awc-spacing-5xlarge)',
        '6xlarge': 'var(--awc-spacing-6xlarge)',
        '7xlarge': 'var(--awc-spacing-7xlarge)',
        'tooltip-arrow': 'var(--awc-tooltip-arrow-size)',
        'title-text-mobile': 'var(--awc-section-spacing-title-text-mobile)',
        'title-text-desktop': 'var(--awc-section-spacing-title-text-desktop)',
        'text-image-mobile': 'var(--awc-section-spacing-text-image-mobile)',
        'text-image-desktop': 'var(--awc-section-spacing-text-image-desktop)',
        'headline-title-mobile': 'var(--awc-section-spacing-headline-title-mobile)',
        'headline-title-desktop': 'var(--awc-section-spacing-headline-title-desktop)',
        'button-text-mobile': 'var( --awc-section-spacing-button-text-mobile)',
        'button-text-desktop': 'var( --awc-section-spacing-button-text-desktop)',
        'button-button-mobile': 'var( --awc-section-spacing-button-button-mobile)',
        'button-button-desktop': 'var( --awc-section-spacing-button-button-desktop)',
        input: {
          sm: 'var(--awc-input-spacing-small)',
          md: 'var(--awc-input-spacing-medium)',
          lg: 'var(--awc-input-spacing-large)',
        }
      },
      gap : {
        card: 'var(--awc-card-padding)',
        medium : 'var(--awc-spacing-medium)',
      },
      letterSpacing: {
        input: 'var(--awc-input-letter-spacing)',
      },
      padding: {
      'section-mobile': 'var(--awc-section-padding-y-mobile)',
      'section-desktop': 'var(--awc-section-padding-y-desktop)',
        card: 'var(--awc-card-padding)',
        panel: 'var(--awc-panel-padding)',
        tooltip: {
          y: 'var(--awc-tooltip-padding-y)',
          x: 'var(--awc-tooltip-padding-x)',
        },
      },
      borderWidth: {
        card: 'var(--awc-card-border-width)',
        panel: 'var(--awc-panel-border-width)',
        input: 'var(--awc-input-border-width)',
      },
      borderRadius: {
        none: 'var(--awc-border-radius-none)',
        small: 'var(--awc-border-radius-small)',
        medium: 'var(--awc-border-radius-medium)',
        large: 'var(--awc-border-radius-large)',
        '2xlarge': 'var(--awc-border-radius-2xlarge)',
        '3xlarge': 'var(--awc-border-radius-3xlarge)',
        xlarge: 'var(--awc-border-radius-xlarge)',
        circle: 'var(--awc-border-radius-circle)',
        pill: 'var(--awc-border-radius-pill)',
        tooltip: 'var(--awc-tooltip-border-radius)',
        badge: 'var(--awc-bagde-border-radius)',
        button: 'var(--awc-button-border-radius)',
        tag: 'var(--awc-tag-border-radius)',
        panel: 'var(--awc-panel-border-radius)',
        card: 'var(--awc-card-border-radius)',
        input: {
          sm: 'var(--awc-input-border-radius-small)',
          md: 'var(--awc-input-border-radius-medium)',
          lg: 'var(--awc-input-border-radius-large)',
        },
      },
      zIndex: {
        tooltip: 'var(--awc-z-index-tooltip)',
        toast: 'var(--awc-z-index-toast)',
        dropdown: 'var(--awc-z-index-dropdown)',
        dialog: 'var(--awc-z-index-dialog)',
        drawer: 'var(--awc-z-index-drawer)',
      },
      lineHeight: {
        normal: 'var(--awc-line-height-normal)',
        dense: 'var(--awc-line-height-dense)',
        loose: 'var(--awc-line-height-loose)',
        looser: 'var(--awc-line-height-looser)',
        denser: 'var(--awc-line-height-denser)',
        tooltip: 'var(--awc-tooltip-line-height)',
        'input-sm': 'var(--awc-input-height-small)',
        'input-md': 'var(--awc-input-height-medium)',
        'input-lg': 'var(--awc-input-height-large)',
      },
      letterSpacing: {
        normal: 'var(--awc-letter-spacing-normal)',
        dense: 'var(--awc-letter-spacing-dense)',
        denser: 'var(--awc-letter-spacing-denser)',
        loose: 'var(--awc-letter-spacing-loose)',
        looser: 'var(--awc-letter-spacing-looser)',
      },
      transitionDuration: {
        xfast: 'var(--awc-transition-xfast)',
        fast: 'var(--awc-transition-fast)',
        medium: 'var(--awc-transition-medium)',
        slow: 'var(--awc-transition-slow)',
        xslow: 'var(--awc-transition-xslow)',
      },
      breakpoints: {
        figma: 'var(--awc-breakpoint-figma)',
        '2xlarge': 'var(--awc-breakpoint-2xlarge)',
        xlarge: 'var(--awc-breakpoint-xlarge)',
        large: 'var(--awc-breakpoint-large)',
        medium: 'var(--awc-breakpoint-medium)',
        small: 'var(--awc-breakpoint-small)',
      },
      fontFamily: {
        sans: 'var(--awc-font-sans), -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
        serif: 'var(--awc-font-serif),-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
        mono: 'var(--awc-font-mono), -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
        heading: 'var(--awc-font-heading), -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
        input: 'var(--awc-input-font-family), -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
        tooltip: 'var(--awc-tooltip-font-family), -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
      },
      fontWeight: {
        light: 'var(--awc-font-weight-light)',
        normal: 'var(--awc-font-weight-normal)',
        medium: 'var(--awc-font-weight-medium)',
        semibold: 'var(--awc-font-weight-semibold)',
        bold: 'var(--awc-font-weight-bold)',
        input: 'var(--awc-input-font-weight)',
        tooltip: 'var(--awc-tooltip-font-weight)',
      },
      boxShadow: {
        'xsmall-blur': 'var(--awc-shadow-xsmall-blur)',
        'xsmall-x': 'var(--awc-shadow-xsmall-x)',
        'xsmall-y': 'var(--awc-shadow-xsmall-y)',
        'xsmall-color': 'var(--awc-shadow-xsmall-color)',
        'xsmall-spread': 'var(--awc-shadow-xsmall-spread)',
        'small-x': 'var(--awc-shadow-small-x)',
        'small-y': 'var(--awc-shadow-small-y)',
        'small-color': 'var(--awc-shadow-small-color)',
        'small-blur': 'var(--awc-shadow-small-blur)',
        'small-spread': 'var(--awc-shadow-small-spread)',
        'medium-x': 'var(--awc-shadow-medium-x)',
        'medium-y': 'var(--awc-shadow-medium-y)',
        'medium-color': 'var(--awc-shadow-medium-color)',
        'medium-blur': 'var(--awc-shadow-medium-blur)',
        'medium-spread': 'var(--awc-shadow-medium-spread)',
        'large-x': 'var(--awc-shadow-large-x)',
        'large-y': 'var(--awc-shadow-large-y)',
        'large-color': 'var(--awc-shadow-large-color)',
        'large-blur': 'var(--awc-shadow-large-blur)',
        'large-spread': 'var(--awc-shadow-large-spread)',
        'xlarge-x': 'var(--awc-shadow-xlarge-x)',
        'xlarge-y': 'var(--awc-shadow-xlarge-y)',
        'xlarge-color': 'var(--awc-shadow-xlarge-color)',
        'xlarge-blur': 'var(--awc-shadow-xlarge-blur)',
        'xlarge-spread': 'var(--awc-shadow-xlarge-spread)',
      },
      ringWidth: {
        focus: 'var(--awc-focus-ring-width)',
      },
      ringOffsetWidth: {
        focus: 'var(--awc-focus-ring-offset)',
        'input-focus': 'var(--awc-input-focus-ring-offset)',
        'input-required-content': 'var(--awc-input-required-content-offset)',
      },
      container: {
        center: true,
        padding: {
            'DEFAULT': '1rem',
            'sm': '2.5rem',
            'md': '2.25rem',
            'lg': '2.75rem',
            'xl': '2.5rem',
            '2xl': '3rem',
        },
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(.4,0,.1,1)',
      },
      rotate: {
        '360': '360deg',
      }
    },
  },
  plugins: [
    typography,
    plugin(function ({ addVariant }) {
      addVariant('is-active', ['&.is-active', '.is-active &']);
      addVariant('is-open', ['&.is-open', '.is-open &']);
      addVariant('visible', ['&.is-visible', '.is-visible &']);
      addVariant('keyboard', '.tab-active &');
    }),
  ],
};

export default config;
